# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: e36889c
_src_path: gh:andyrids/copier-python-package
git_platform: GitLab
git_repository: https://gitlab.com/andyrids/pkgdx
gitlab_user: andyrids
install_just_dependency: false
package_description: ''
package_name: pkgdx
python_version: 3.13.13
requires_python: '>=3.12'
task_runner: Just
user_email: 52859097+andyrids@users.noreply.github.com
user_name: Andrew Ridyard
