- id: pytack-format
  name: Format [Ruff]
  description: "Formats code using Ruff."
  entry: pytack-format-hook
  args: ["--exit-non-zero-on-format"]
  language: python
  types_or: ["python", "pyi"]
  require_serial: true
  pass_filenames: false
  
- id: pytack-lint
  name: Lint [Ruff]
  description: "Lints code using Ruff."
  entry: pytack-lint-hook
  args: ["--fix", "--exit-non-zero-on-fix"]
  language: python
  types_or: ["python", "pyi"]
  require_serial: true
  pass_filenames: false
  
- id: pytack-typing
  name: Typing [Mypy]
  description: "Checks type annotations using Mypy."
  entry: pytack-typing-hook
  args: []
  language: python
  types_or: ["python", "pyi"]
  exclude: "tests/"
  require_serial: true
  pass_filenames: true
  
- id: pytack-markdown
  name: Markdown [PyMarkdown]
  description: "Lints Markdown files using PyMarkdown."
  entry: pytack-markdown-hook
  args: []
  language: python
  types_or: ["markdown"]
  require_serial: true
  pass_filenames: true

- id: pytack-secrets
  name: Detect Secrets [detect-secrets]
  description: "Detects secrets in code using detect-secrets."
  entry: pytack-secrets-hook
  args: ["--baseline", ".secrets.baseline", "--no-verify"]
  language: python
  types_or: ["python", "pyi"]
  exclude: "(\\.secrets\\.baseline|.*\\.lock)"
  require_serial: true
  pass_filenames: true
  stages: ["pre-commit"]
