[project]
name = "pkgdev"
version = "0.1.0"
description = "A package to centralise standards across Python projects."
readme = "README.md"
license = "Apache-2.0"
license-files = ["LICEN[CS]E*", "COPYRIGHT"]
authors = [
    { name = "Andrew Ridyard", email = "andyrids.culprit320@passmail.com" },
]
requires-python = ">=3.10"
keywords = []
classifiers = [
    # 3 - Alpha | 4 - Beta | 5 - Production/Stable
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Typing :: Typed",
]
dependencies = [
    "detect-secrets",
    "mypy",
    "prek",
    "pymarkdownlnt>=0.9.37",
    "rich>=15.0.0",
    "ruff",
]

[dependency-groups]
dev = [
    "coverage>=7.14.1",
    "pytest",
]

[project.scripts]
pkgdev = "pkgdev.__main__:main"
pkgdev-secrets = "pkgdev.__main__:detect_secrets"
pkgdev-format = "pkgdev.__main__:ruff_format"
pkgdev-lint = "pkgdev.__main__:ruff_lint"
pkgdev-markdown = "pkgdev.__main__:pymarkdown_lint"
pkgdev-typing = "pkgdev.__main__:mypy_typing"

[project.urls]
Repository = "https://gitlab.com/python-standards/pkgdev"
Issues = "https://gitlab.com/python-standards/pkgdev/issues"
Changelog = "https://gitlab.com/python-standards/pkgdev/blob/main/CHANGELOG.md"

[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.hatch.version]
source = "vcs"

[tool.hatch.version.raw-options]
local_scheme = "no-local-version"
version_scheme = "guess-next-dev"

[tool.pytest.ini_options]
addopts = ["--import-mode=importlib"]
tmp_path_retention_policy = "failed"
