exclude = []
indent-width = 4
line-length = 79

[format]
indent-style = "space"
line-ending = "auto"
quote-style = "double"

[lint]
select = [
    "ANN001", # flake8-annotations (missing-type-function-argument)
    "ANN002", # flake8-annotations (missing-type-args)
    "ANN003", # flake8-annotations (missing-type-kwargs)
    "ANN201", # flake8-annotations (missing-return-type-undocumented-public-function)
    "ANN202", # flake8-annotations (missing-return-type-private-function)
    "D1",     # pydocstyle (undocumented-* ruleset)
    "D400",   # pydocstyle (missing-trailing-period)
    "D403",   # pydocstyle (first-word-uncapitalized)
    "D417",   # pydocstyle (undocumented-param)
    "D419",   # pydocstyle (empty-docstring)
    "E",      # pycodestyle (error ruleset)
    "ERA",    # commented out code
    "F401",   # pyflakes (unused-import)
    "F841",   # pyflakes (unused-variable)
    "I002",   # isort (missing-required-import)
    "LOG",    # flake8-logging (logging)
    "NPY001", # NumPy-specific rules (numpy-deprecated-type-alias)
    "NPY003", # NumPy-specific rules (numpy-deprecated-function)
    "PERF",   # perflint (performance)
    "RET501", # flake8-return (unnecessary-return-none)
    "RET503", # flake8-return (implicit-return)
    "RET503", # flake8-return (implicit-return)
    "T100",   # flake8-debugger (debugger)
    "T201",   # flake8-print (print)
    "TRY002", # tryceratops (raise-vanilla-class)
    "TRY003", # tryceratops (raise-vanilla-args)
    "TRY004", # tryceratops (type-check-without-type-error)
    "TRY300", # tryceratops (try-consider-else)
    "TRY401", # tryceratops (verbose-log-message)
    "W",      # pycodestyle (warning ruleset)
    "C90",    # McCabe complexity (complex-structure)
]

[lint.pydocstyle]
convention = "google"