#:schema https://raw.githubusercontent.com/j178/prek/refs/heads/master/prek.schema.json

[[repos]]
repo = "https://gitlab.com/andyrids/pytack"
rev = "v0.1.0rc5"

[[repos.hooks]]
id = "pytack-lint"
name = "Lint [Ruff]"

[[repos.hooks]]
id = "pytack-format"
name = "Format [Ruff]"

[[repos.hooks]]
id = "pytack-markdown"
name = "Check Markdown [PyMarkdown]"

[[repos.hooks]]
id = "pytack-typing"
name = "Typing [Mypy]"

[[repos.hooks]]
id = "pytack-secrets"
name = "Detect Secrets [detect-secrets]"

[[repos]]
repo = "builtin"

[[repos.hooks]]
id = "check-toml"
name = "Check TOML [Builtin]"

[[repos.hooks]]
id = "check-yaml"
name = "Check YAML [Builtin]"

[[repos.hooks]]
id = "detect-private-key"
name = "Detect PEM [Builtin]"