[project]
name = "testing"
version = "0.1.0"
description = "A pkgdx consumer for local testing"
authors = [
    { name = "andyrids", email = "andyrids.culprit320@passmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "pkgdx",
]

[project.scripts]
testing = "testing:main"

[build-system]
requires = ["uv_build>=0.11.20,<0.12.0"]
build-backend = "uv_build"

[tool.uv.sources]
pkgdx = { workspace = true }
